/**
 * Orphan Report History Component
 * Implements UC-6.9: View Report History
 *
 * Displays list of previously generated orphan reports with:
 * - Report Name/Period
 * - Generation Date
 * - Generated By
 * - Filters Applied
 * - Orphan Count
 * - Actions (View, Export, Delete)
 *
 * Access:
 * - Charity users: Only see their own reports
 * - Admin/Super Admin: See all reports
 */

import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';

import { OrphanReportService } from '../services/orphan-report.service';
import { OrphanReportHistoryDto } from '../models/periodic-orphan-report.model';
import { LoadingComponent } from '../../../shared/components/loading/loading.component';
import { PaginationComponent } from '../../../shared/components/pagination/pagination.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';

import { BreadcrumbComponent } from '../../../shared/components/breadcrumb/breadcrumb.component';
@Component({
  selector: 'app-orphan-report-history',
  standalone: true,
  imports: [
    BreadcrumbComponent,
    EmptyStateComponent,

    CommonModule,
    FormsModule,
    TranslateModule,
    LoadingComponent,
    PaginationComponent,
    EmptyStateComponent
  ],
  templateUrl: './orphan-report-history.component.html',
  styleUrls: ['./orphan-report-history.component.scss']
})
export class OrphanReportHistoryComponent implements OnInit {
  // Data
  reports: OrphanReportHistoryDto[] = [];
  totalCount = 0;
  loading = false;

  // Pagination
  currentPage = 1;
  pageSize = 20;

  // Filter
  dateFrom?: string;
  dateTo?: string;

  // User role
  isAdminOrSuperAdmin = false; // Would come from auth service

  constructor(
    private orphanReportService: OrphanReportService
  ) {}

  ngOnInit(): void {
    this.loadReports();
  }

  /**
   * Load report history - UC-6.9
   */
  loadReports(): void {
    this.loading = true;

    this.orphanReportService.getReportHistory(this.currentPage, this.pageSize).subscribe({
      next: (result) => {
        this.reports = result.items;
        this.totalCount = result.totalCount;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading report history:', error);
        this.loading = false;
      }
    });
  }

  /**
   * Handle page change
   */
  onPageChange(page: number): void {
    this.currentPage = page;
    this.loadReports();
  }

  /**
   * View report details - UC-6.9
   */
  viewReport(reportId: string): void {
    // Navigate to report view
    // This.router.navigate(['/orphan-reports/history', reportId]);
    console.log('View report:', reportId);
  }

  /**
   * Export report - UC-6.7
   */
  exportReport(reportId: string, format: string): void {
    // Re-export existing report
    this.orphanReportService.getReportHistoryEntry(reportId).subscribe({
      next: (report) => {
        // Trigger export
        console.log('Export report:', report, 'format:', format);
      },
      error: (error) => {
        console.error('Error exporting report:', error);
      }
    });
  }

  /**
   * Delete report - UC-6.9
   */
  deleteReport(reportId: string, reportName: string): void {
    if (confirm(`Are you sure you want to delete report "${reportName}"?`)) {
      this.orphanReportService.deleteReportHistoryEntry(reportId).subscribe({
        next: () => {
          this.loadReports();
        },
        error: (error) => {
          console.error('Error deleting report:', error);
        }
      });
    }
  }

  /**
   * Filter by date range
   */
  applyFilter(): void {
    // TODO: Implement date range filtering
    this.currentPage = 1;
    this.loadReports();
  }

  /**
   * Clear filters
   */
  clearFilter(): void {
    this.dateFrom = undefined;
    this.dateTo = undefined;
    this.currentPage = 1;
    this.loadReports();
  }

  /**
   * Get file icon based on format
   */
  getFileIcon(format: string): string {
    switch (format.toLowerCase()) {
      case 'excel':
      case 'xlsx':
        return 'fa-file-excel text-success';
      case 'pdf':
        return 'fa-file-pdf text-danger';
      default:
        return 'fa-file text-secondary';
    }
  }

  /**
   * Get format badge class
   */
  getFormatBadgeClass(format: string): string {
    switch (format.toLowerCase()) {
      case 'excel':
      case 'xlsx':
        return 'bg-success';
      case 'pdf':
        return 'bg-danger';
      default:
        return 'bg-secondary';
    }
  }
}
