using AutoMapper;
using IIROSA.Application.DTOs.OfficeProjectManagement;
using IIROSA.Domain.Entities;
using IIROSA.Domain.Entities.Lookups;

namespace IIROSA.Application.Profiles;

/// <summary>
/// AutoMapper Profile for OfficeProject entity
/// Maps between OfficeProject entity and DTOs for all use cases UC-7.1 through UC-7.14
/// </summary>
public class OfficeProjectProfile : Profile
{
    public OfficeProjectProfile()
    {
        // ========== Entity to DTO Mappings ==========

        /// <summary>
        /// OfficeProject to OfficeProjectListDto (for grid display in UC-7.10)
        /// </summary>
        CreateMap<OfficeProject, OfficeProjectListDto>()
            .ForMember(dest => dest.ProjectType,
                opt => opt.MapFrom(src =>
                    src.OfficeProjectType != null ? src.OfficeProjectType.NameAr ?? src.OfficeProjectType.NameEn : null))
            .ForMember(dest => dest.Region,
                opt => opt.MapFrom(src =>
                    src.Region != null ? src.Region.NameAr ?? src.Region.NameEn : null))
            .ForMember(dest => dest.Center,
                opt => opt.MapFrom(src =>
                    src.Center != null ? src.Center.NameAr ?? src.Center.NameEn : null))
            .ForMember(dest => dest.Village,
                opt => opt.MapFrom(src => src.VillageName))
            .ForMember(dest => dest.AssignedCharity,
                opt => opt.MapFrom(src =>
                    src.Charity != null ? src.Charity.Name : null))
            .ForMember(dest => dest.CountryName,
                opt => opt.MapFrom(src =>
                    src.Country != null ? src.Country.NameAr ?? src.Country.NameEn : null));

        /// <summary>
        /// OfficeProject to OfficeProjectDetailDto (for detailed view in UC-7.11)
        /// </summary>
        CreateMap<OfficeProject, OfficeProjectDetailDto>()
            .ForMember(dest => dest.OfficeProjectTypeName,
                opt => opt.MapFrom(src =>
                    src.OfficeProjectType != null ? src.OfficeProjectType.NameAr ?? src.OfficeProjectType.NameEn : null))
            .ForMember(dest => dest.CountryName,
                opt => opt.MapFrom(src =>
                    src.Country != null ? src.Country.NameAr ?? src.Country.NameEn : null))
            .ForMember(dest => dest.RegionName,
                opt => opt.MapFrom(src =>
                    src.Region != null ? src.Region.NameAr ?? src.Region.NameEn : null))
            .ForMember(dest => dest.CenterName,
                opt => opt.MapFrom(src =>
                    src.Center != null ? src.Center.NameAr ?? src.Center.NameEn : null))
            .ForMember(dest => dest.CharityName,
                opt => opt.MapFrom(src =>
                    src.Charity != null ? src.Charity.Name : null))
            //.ForMember(dest => dest.AttachedFileName,
            //    opt => opt.MapFrom(src =>
            //        src.AttachedFile != null ? src.AttachedFile.FileName : null))
            //.ForMember(dest => dest.ProjectReportFileName,
            //    opt => opt.MapFrom(src =>
            //        src.ProjectReportFile != null ? src.ProjectReportFile.FileName : null))
            
            ;

        // ========== DTO to Entity Mappings ==========

        /// <summary>
        /// CreateOfficeProjectDto to OfficeProject (for UC-7.1: Create Office Project)
        /// </summary>
        CreateMap<CreateOfficeProjectDto, OfficeProject>()
            .ForMember(dest => dest.Id,
                opt => opt.Ignore()) // ID is generated by database
            .ForMember(dest => dest.CreatedOn,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.CreatedBy,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.UpdatedOn,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.UpdatedBy,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.OfficeProjectType,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Country,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Region,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Center,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Charity,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.FK_AttachedFileId,
                opt => opt.Ignore()) // Set by service from Document_Attach
            .ForMember(dest => dest.FK_ProjectReportFileId,
                opt => opt.Ignore()); // Set by service from Report_Attach

        /// <summary>
        /// UpdateOfficeProjectDto to OfficeProject (for UC-7.8: Update Project Details)
        /// </summary>
        CreateMap<UpdateOfficeProjectDto, OfficeProject>()
            .ForMember(dest => dest.Id,
                opt => opt.Ignore()) // ID should not be updated
            .ForMember(dest => dest.CreatedOn,
                opt => opt.Ignore()) // Should not be updated
            .ForMember(dest => dest.CreatedBy,
                opt => opt.Ignore()) // Should not be updated
            .ForMember(dest => dest.UpdatedOn,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.UpdatedBy,
                opt => opt.Ignore()) // Set by repository/base class
            .ForMember(dest => dest.OfficeProjectType,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Country,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Region,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Center,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.Charity,
                opt => opt.Ignore()) // Navigation property
            .ForMember(dest => dest.FK_AttachedFileId,
                opt => opt.Ignore()) // Set by service from Document_Attach
            .ForMember(dest => dest.FK_ProjectReportFileId,
                opt => opt.Ignore()); // Set by service from Report_Attach

        // ========== Additional Mappings for Specific DTOs ==========

        /// <summary>
        /// AssignProjectLocationDto to OfficeProject (for location updates - UC-7.5)
        /// </summary>
        CreateMap<AssignProjectLocationDto, OfficeProject>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectName, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectHint, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostEGP, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostSAR, opt => opt.Ignore())
            .ForMember(dest => dest.DonorName, opt => opt.Ignore())
            .ForMember(dest => dest.BeneficiariesCount, opt => opt.Ignore())
            .ForMember(dest => dest.BeneficiariesType, opt => opt.Ignore())
            .ForMember(dest => dest.OfficeProjectType, opt => opt.Ignore())
            .ForMember(dest => dest.Charity, opt => opt.Ignore());

        /// <summary>
        /// MarkProjectCompletedDto to OfficeProject (for project completion - UC-7.9)
        /// </summary>
        CreateMap<MarkProjectCompletedDto, OfficeProject>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectName, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectHint, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostEGP, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostSAR, opt => opt.Ignore())
            .ForMember(dest => dest.OfficeProjectType, opt => opt.Ignore())
            .ForMember(dest => dest.Country, opt => opt.Ignore())
            .ForMember(dest => dest.Region, opt => opt.Ignore())
            .ForMember(dest => dest.Center, opt => opt.Ignore())
            .ForMember(dest => dest.Charity, opt => opt.Ignore());

        /// <summary>
        /// SetProjectBudgetDto to OfficeProject (for budget updates - UC-7.2)
        /// </summary>
        CreateMap<SetProjectBudgetDto, OfficeProject>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectName, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectHint, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.OfficeProjectType, opt => opt.Ignore())
            .ForMember(dest => dest.Country, opt => opt.Ignore())
            .ForMember(dest => dest.Region, opt => opt.Ignore())
            .ForMember(dest => dest.Center, opt => opt.Ignore())
            .ForMember(dest => dest.VillageName, opt => opt.Ignore())
            .ForMember(dest => dest.DonorName, opt => opt.Ignore())
            .ForMember(dest => dest.BeneficiariesCount, opt => opt.Ignore())
            .ForMember(dest => dest.BeneficiariesType, opt => opt.Ignore())
            .ForMember(dest => dest.Charity, opt => opt.Ignore());

        /// <summary>
        /// SetBeneficiariesCountDto to OfficeProject (for beneficiaries updates - UC-7.4)
        /// </summary>
        CreateMap<SetBeneficiariesCountDto, OfficeProject>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectName, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectHint, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectDate, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedOn, opt => opt.Ignore())
            .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostEGP, opt => opt.Ignore())
            .ForMember(dest => dest.ProjectCostSAR, opt => opt.Ignore())
            .ForMember(dest => dest.DonorName, opt => opt.Ignore())
            .ForMember(dest => dest.OfficeProjectType, opt => opt.Ignore())
            .ForMember(dest => dest.Country, opt => opt.Ignore())
            .ForMember(dest => dest.Region, opt => opt.Ignore())
            .ForMember(dest => dest.Center, opt => opt.Ignore())
            .ForMember(dest => dest.VillageName, opt => opt.Ignore())
            .ForMember(dest => dest.Charity, opt => opt.Ignore());
    }
}
