<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IIROSA.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ServiceCollectionExtensions.cs~RF256399f4.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IIROSA.Domain\IIROSA.Domain.csproj" />
    <ProjectReference Include="..\..\Framework\Framework.Core\Framework.Core.csproj" />
    <ProjectReference Include="..\..\Framework\Framework.Identity\Framework.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>

</Project>
