// <auto-generated />
using System;
using Framework.Core.SharedServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Framework.Core.Migrations
{
    [DbContext(typeof(CommonsDbContext))]
    [Migration("20230724081618_AddHostingRequestTemplate")]
    partial class AddHostingRequestTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubjectEn")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationTemplate", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyAr = " <html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nتم اصدار تصريح دخول للزائر {VisitorName}<br/>\r\n صاحب هوية رقم {VisitorId} <br/>\r\nتاريخ الزيارة: {VisitDate} <br/>\r\nوقت الزيارة: {VisitTime}   <br/>\r\nزيارة للموظف: {EmployeeName} <br/>\r\n\r\n\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = " <html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nEntry permit has been issued to vistor{VisitorName} <br/>\r\nWith Identity {VisitorId} <br/>\r\nVisit Date: {VisitDate}	<br/>\r\nVisit time: {VisitTime} <br/>\r\nVisiting employee: {EmployeeName} <br/>\r\n\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "AccessRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "تصريح دخول",
                            SubjectEn = "Access Request"
                        },
                        new
                        {
                            Id = 2,
                            BodyAr = "<html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nلقد تمت الموافقة على طلبكم الخاص بطلب الضيافة\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = "<html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nYour request for hospitality has been approved.\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "AcceptHostingRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "قبول طلب الضيافة",
                            SubjectEn = "Accept Hosting Request"
                        },
                        new
                        {
                            Id = 3,
                            BodyAr = "<html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nلقد تم رفض طلبكم الخاص بطلب الضيافة\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = "<html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nYour request for hospitality has been rejected.\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "RejectHostingRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "رفض طلب الضيافة",
                            SubjectEn = "Reject Hosting Request"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationType", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "البريد الالكترونى",
                            NameEn = "Email"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSticky")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Integration",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "CamundaUrl",
                            Value = "http://192.168.1.136:8080/",
                            ValueType = "string"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationTemplate", b =>
                {
                    b.HasOne("Framework.Core.SharedServices.Entities.NotificationType", "NotificationType")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationType", b =>
                {
                    b.Navigation("NotificationTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
