// <auto-generated />
using System;
using Framework.Core.SharedServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Framework.Core.Migrations
{
    [DbContext(typeof(CommonsDbContext))]
    [Migration("20231102073432_update attachement")]
    partial class updateattachement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.ToTable("Attachment", "common");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.AttachmentContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("AttachmentContent", "common");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.AttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AllowedFilesExtension")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageMaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("ImageMaxWidth")
                        .HasColumnType("int");

                    b.Property<bool>("IsImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSizeInMegabytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AttachmentType", "common");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasMaxLength(6000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6000)");

                    b.Property<string>("Host")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logger")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Thread")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Log", "common");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubjectEn")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationTemplate", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyAr = " <html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nتم اصدار تصريح دخول للزائر {VisitorName}<br/>\r\n صاحب هوية رقم {VisitorId} <br/>\r\nتاريخ الزيارة: {VisitDate} <br/>\r\nوقت الزيارة: {VisitTime}   <br/>\r\nزيارة للموظف: {EmployeeName} <br/>\r\n\r\n\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = " <html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nEntry permit has been issued to vistor{VisitorName} <br/>\r\nWith Identity {VisitorId} <br/>\r\nVisit Date: {VisitDate}	<br/>\r\nVisit time: {VisitTime} <br/>\r\nVisiting employee: {EmployeeName} <br/>\r\n\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "AccessRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "تصريح دخول",
                            SubjectEn = "Access Request"
                        },
                        new
                        {
                            Id = 2,
                            BodyAr = "<html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nلقد تمت الموافقة على طلبكم الخاص بطلب الضيافة\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = "<html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nYour request for hospitality has been approved.\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "AcceptHostingRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "قبول طلب الضيافة",
                            SubjectEn = "Accept Hosting Request"
                        },
                        new
                        {
                            Id = 3,
                            BodyAr = "<html dir=\"rtl\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:right;padding:0 10px;\">\r\n								  <p>\r\nلقد تم رفض طلبكم الخاص بطلب الضيافة\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            BodyEn = "<html dir=\"ltr\" >\r\n \r\n							   <h3 style=\"font-weight:normal;text-align:left;padding:0 10px;\">\r\n								  <p>\r\nYour request for hospitality has been rejected.\r\n</p>\r\n								\r\n							   </h3>\r\n</html>\r\n\r\n\r\n",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "RejectHostingRequest",
                            NotificationTypeId = 1,
                            SubjectAr = "رفض طلب الضيافة",
                            SubjectEn = "Reject Hosting Request"
                        },
                        new
                        {
                            Id = 4,
                            BodyAr = "<!DOCTYPE HTML\r\n	PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" dir=\"rtl\">\r\n\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n	<title>هيئة الحكومية الرقمية</title>\r\n</head>\r\n\r\n<body dir=\"rtl\" style=\"padding:0px\">\r\n	\r\n	<table width=\"1024\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n		<tr>\r\n			<td class=\"email_conts\"\r\n				style=\"padding:10px 20px;  font:11px Segoe UI,tahoma;  line-height:20px;  color:#404040;  text-align:right; border-top:none\">\r\n				{Body}\r\n				</br>\r\n				<h3>وتقبلوا فائق الاحترام</h3>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td class=\"email_footer\" width=\"1024\"\r\n				style=\"padding:10px 0;  background-color:#202020;  color:#fff;  font:11px Segoe UI,tahoma;  text-align:center\">\r\n				لمقترحاتكم وملاحظاتكم راسلونا على البريد الإلكتروني: <a href=\"#\"\r\n					style=\"color:#fff;  font:11px Segoe UI,tahoma\">support@pgd.gov.sa</a>\r\n			</td>\r\n		</tr>\r\n	</table>\r\n</body>\r\n\r\n</html>",
                            BodyEn = "<!DOCTYPE HTML\r\n	PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" dir=\"rtl\">\r\n\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n	<title>DGA</title>\r\n</head>\r\n\r\n<body dir=\"ltr\" style=\"padding:0px\">\r\n	<table width=\"1024\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n		<tr>\r\n			<td class=\"email_conts\"\r\n				style=\"padding:10px 20px;  font:11px Segoe UI,tahoma;  line-height:20px;  color:#404040;  text-align:right; border-top:none\">\r\n				{Body}\r\n				</br>\r\n				<h3 style=\"text-align:justify;font-weight:normal;\">Yours Sincerely </h3>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td class=\"email_footer\" width=\"1024\"\r\n				style=\"padding:10px 0;  background-color:#202020;  color:#fff;  font:11px Segoe UI,tahoma;  text-align:center\">\r\n				For your suggestions and comments, send us an e-mail: <a href=\"#\"\r\n					style=\"color:#fff;  font:11px Segoe UI,tahoma\">support@pgd.gov.sa</a>\r\n			</td>\r\n		</tr>\r\n	</table>\r\n</body>\r\n\r\n</html>",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "CommonEmailStructure",
                            NotificationTypeId = 1,
                            SubjectAr = "هيئة الحكومية الرقمية",
                            SubjectEn = "DGA"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationType", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "البريد الالكترونى",
                            NameEn = "Email"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSticky")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SystemSetting", "common");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Integration",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "CamundaUrl",
                            Value = "http://localhost:8080/",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "SmtpServer",
                            Value = "192.168.1.166",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "SmtpUserName",
                            Value = "",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "SmtpPassword",
                            Value = "",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "SmtpEnableSSL",
                            Value = "False",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "SmtpPort",
                            Value = "25",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "EmailFromName",
                            Value = "DGA",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Notifications",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "EmailFromAddress",
                            Value = "info@suredemos.com",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Integration",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "AttachmentsPath",
                            Value = "Attachments",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Integration",
                            IsActive = true,
                            IsSecure = false,
                            IsSticky = false,
                            Name = "AttachmentsServer",
                            Value = "C:\\inetpub\\wwwroot\\DGA-Internal",
                            ValueType = "string"
                        });
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.Attachment", b =>
                {
                    b.HasOne("Framework.Core.SharedServices.Entities.AttachmentType", "AttachmentType")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.Core.SharedServices.Entities.AttachmentContent", "AttachmentContent")
                        .WithOne("Attachment")
                        .HasForeignKey("Framework.Core.SharedServices.Entities.Attachment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachmentContent");

                    b.Navigation("AttachmentType");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationTemplate", b =>
                {
                    b.HasOne("Framework.Core.SharedServices.Entities.NotificationType", "NotificationType")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.AttachmentContent", b =>
                {
                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.AttachmentType", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Framework.Core.SharedServices.Entities.NotificationType", b =>
                {
                    b.Navigation("NotificationTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
