<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup Label="Globals">
		<SccProjectName></SccProjectName>
		<SccProvider></SccProvider>
		<SccAuxPath></SccAuxPath>
		<SccLocalPath></SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SmartBreadcrumbs" Version="3.5.3" />
		<PackageReference Include="System.DirectoryServices.AccountManagement" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Framework.Core\Framework.Core.csproj" />
	</ItemGroup>


</Project>
