namespace IIROSA.Application.DTOs.OrphanReport;

/// <summary>
/// Complete Orphan Report Result - UC-6.1
/// </summary>
public class OrphanReportResultDto
{
    /// <summary>
    /// Report metadata - UC-6.1
    /// </summary>
    public OrphanReportMetadataDto Metadata { get; set; } = new();

    /// <summary>
    /// Summary statistics - UC-6.1
    /// </summary>
    public OrphanReportSummaryDto Summary { get; set; } = new();

    /// <summary>
    /// Detailed orphan list - UC-6.1
    /// </summary>
    public List<OrphanReportDto> Orphans { get; set; } = new();

    /// <summary>
    /// §14.U.11 detailed periodic-report rows (UC-ORR-11) — the extract this
    /// endpoint now carries alongside the legacy orphan-registry pull.
    /// </summary>
    public List<OrphanReportDetailRow> Reports { get; set; } = new();

    /// <summary>Matching report rows before the extract cap (the cap bounds rows, not the count).</summary>
    public int ReportsTotalCount { get; set; }

    /// <summary>
    /// Generated timestamp
    /// </summary>
    public DateTime GeneratedOn { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Report Metadata - UC-6.1
/// </summary>
public class OrphanReportMetadataDto
{
    public DateTime FromDate { get; set; }
    public DateTime ToDate { get; set; }

    // Applied filters
    public Guid? CharityId { get; set; }
    public string? CharityName { get; set; }
    public int? RegionId { get; set; }
    public string? RegionName { get; set; }
    public int? CenterId { get; set; }
    public string? CenterName { get; set; }
    public string? SponsorshipStatus { get; set; }
    public int? AgeFrom { get; set; }
    public int? AgeTo { get; set; }
    public string? Gender { get; set; }

    // Report options
    public bool IncludeFamilyDetails { get; set; }
    public bool IncludeContactInformation { get; set; }
    public bool IncludeEducationDetails { get; set; }
    public bool IncludeHealthDetails { get; set; }
    public bool GroupByCharity { get; set; }

    // Generated by
    public Guid? GeneratedByUserId { get; set; }
    public string? GeneratedByUserName { get; set; }
}

/// <summary>
/// §14.U.11 detailed extract row (UC-ORR-11) — the periodic report's dimensions
/// plus orphan identity and charity name. The general-purpose pull that
/// 9-12/9-13 specialise with a review-state predicate.
/// </summary>
public class OrphanReportDetailRow
{
    public Guid ReportId { get; set; }
    public string? ReportNo { get; set; }
    public DateTime ReportDate { get; set; }
    public DateTime? ReportPeriodFrom { get; set; }
    public DateTime? ReportPeriodTo { get; set; }

    // Orphan identity + charity
    public string OrphanCode { get; set; } = string.Empty;
    public string OrphanName { get; set; } = string.Empty;
    public string? CharityName { get; set; }

    // Review state
    public string ReviewStatus { get; set; } = "Pending";
    public bool Reviewed { get; set; }
    public bool IsAccepted { get; set; }
    public bool IsRefused { get; set; }
    public string? RefuseReason { get; set; }

    // Key report dimensions
    public string? SchoolType { get; set; }
    public string? School { get; set; }
    public string? Faculty { get; set; }
    public string? Specialization { get; set; }
    public string? Grade { get; set; }
    public string? EducationDegree { get; set; }
    public int? EducationalLevelId { get; set; }
    public string? EducationalLevelName { get; set; }
    public string? MedicalStatus { get; set; }
    public string? Disease { get; set; }
    public string? Disability { get; set; }
    public bool? Married { get; set; }
    public DateTime? MarriageDate { get; set; }
    public bool? Dead { get; set; }
    public DateTime? DeathDate { get; set; }
}
