namespace IIROSA.Application.DTOs.OrphanReport;

/// <summary>
/// Complete Orphan Report Result - UC-6.1
/// </summary>
public class OrphanReportResultDto
{
    /// <summary>
    /// Report metadata - UC-6.1
    /// </summary>
    public OrphanReportMetadataDto Metadata { get; set; } = new();

    /// <summary>
    /// Summary statistics - UC-6.1
    /// </summary>
    public OrphanReportSummaryDto Summary { get; set; } = new();

    /// <summary>
    /// Detailed orphan list - UC-6.1
    /// </summary>
    public List<OrphanReportDto> Orphans { get; set; } = new();

    /// <summary>
    /// Generated timestamp
    /// </summary>
    public DateTime GeneratedOn { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Report Metadata - UC-6.1
/// </summary>
public class OrphanReportMetadataDto
{
    public DateTime FromDate { get; set; }
    public DateTime ToDate { get; set; }

    // Applied filters
    public Guid? CharityId { get; set; }
    public string? CharityName { get; set; }
    public int? RegionId { get; set; }
    public string? RegionName { get; set; }
    public int? CenterId { get; set; }
    public string? CenterName { get; set; }
    public string? SponsorshipStatus { get; set; }
    public int? AgeFrom { get; set; }
    public int? AgeTo { get; set; }
    public string? Gender { get; set; }

    // Report options
    public bool IncludeFamilyDetails { get; set; }
    public bool IncludeContactInformation { get; set; }
    public bool IncludeEducationDetails { get; set; }
    public bool IncludeHealthDetails { get; set; }
    public bool GroupByCharity { get; set; }

    // Generated by
    public Guid? GeneratedByUserId { get; set; }
    public string? GeneratedByUserName { get; set; }
}
